# Generated by Django 6.1.1 on 2026-10-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
